name: AWS Lambda - CI App

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        
          - name: Run tests
            run: make test
            working-directory: aws-lambda/app
    
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        
          - name: Build
            run: make build
            working-directory: aws-lambda/app

